name: Update README.md files with terraform-docs on Merge

on:
  push:
    branches:
      - main
    paths:
      - modules/**/*.tf
      - templates/**/*.tf

permissions:
  contents: write

jobs:
  update-readmes:
    name: Update README.md files with terraform-docs (single commit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract ticket ID from last commit
        id: ticket
        shell: bash
        run: |
          TICKET=$(git log -1 --pretty=%B | grep -oE 'NCP-[0-9]+' || echo "NCP-XXXX")
          echo "ticket=$TICKET" >> "$GITHUB_OUTPUT"

      - name: Get changed Terraform directories
        id: get_dirs
        shell: bash
        run: |
          BEFORE_COMMIT="${{ github.event.before || 'HEAD~1' }}"
          CHANGED=$(git diff --name-only "$BEFORE_COMMIT" "${{ github.sha }}" \
            | grep -E '^(modules|templates)/.*\.tf$' \
            | xargs -n1 dirname \
            | sort -u)
          echo "Changed directories:"
          echo "$CHANGED"
          if [ -z "$CHANGED" ]; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "$CHANGED" > changed_dirs.txt
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run terraform-docs recursively on modules and templates
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .                 # Root directory
          recursive: true                # Recursively go into all subfolders
          output-method: inject
          output-file: README.md
          git-push: false

      - name: Fix Git permissions
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          sudo chown -R "$(whoami)":"$(whoami)" .git/

      - name: Commit and push the updated README.md files
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          git config user.name "tester"
          git config user.email "tester@users.noreply.github.com"
          
          git add modules/**/README.md templates/**/README.md
          git commit -m "${{ steps.ticket.outputs.ticket }}: Auto-update README.md with terraform-docs" || echo "No changes to commit"

          BRANCH="${GITHUB_REF#refs/heads/}"
          git pull origin "$BRANCH" --rebase
          git push origin "$BRANCH"
