name: Update READMEs with terraform-docs on Merge

on:
  push:
    branches:
      - main
    paths:
      - modules/**/*.tf
      - templates/**/*.tf

permissions:
  contents: write

jobs:
  update-readmes:
    name: Update README.md files with terraform-docs (single commit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract ticket ID from last commit
        id: ticket
        shell: bash
        run: |
          TICKET=$(git log -1 --pretty=%B | grep -oE 'NCP-[0-9]+' || echo "NCP-XXXX")
          echo "ticket=$TICKET" >> "$GITHUB_OUTPUT"

      - name: Get changed Terraform directories
        id: get_dirs
        shell: bash
        run: |
          BEFORE_COMMIT="${{ github.event.before || 'HEAD~1' }}"
          CHANGED=$(git diff --name-only "$BEFORE_COMMIT" "${{ github.sha }}" \
            | grep -E '^(modules|templates)/.*\.tf$' \
            | xargs -n1 dirname \
            | sort -u | uniq)

          echo "Changed directories:"
          echo "$CHANGED"

          if [[ -z "$CHANGED" ]]; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "$CHANGED" > changed_dirs.txt
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install terraform-docs (locally, no sudo)
        if: steps.get_dirs.outputs.no_changes == 'false'
        run: |
          curl -sLo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          mkdir -p $HOME/.local/bin
          mv terraform-docs $HOME/.local/bin/
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          terraform-docs --version

      - name: Run terraform-docs in each directory
        if: steps.get_dirs.outputs.no_changes == 'false'
        run: |
          while read -r dir; do
            if [[ -f "$dir/README.md" ]]; then
              echo "Updating $dir/README.md"
              terraform-docs markdown table "$dir" > "$dir/README.md"
            else
              echo "Skipping $dir — no README.md found"
            fi
          done < changed_dirs.txt

      - name: Commit and push all updated README.md files
        if: steps.get_dirs.outputs.no_changes == 'false'
        run: |
          git config user.name "testing"
          git config user.email "testing@users.noreply.github.com"
          BRANCH="${GITHUB_REF#refs/heads/}"
          git pull origin "$BRANCH" --ff-only || true
          git add modules/**/README.md templates/**/README.md || true
          git commit -m "${{ steps.ticket.outputs.ticket }}: Auto-update all README.md with terraform-docs" || echo "No changes to commit"
          git push origin "$BRANCH"


