name: Update READMEs with terraform-docs on Merge

on:
  push:
    branches:
      - main
    paths:
      - templates/**/*.tf
      - modules/**/*.tf

permissions:
  contents: write

jobs:
  update-readmes:
    name: Update README.md for modules and templates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed Terraform directories
        id: get_dirs
        shell: bash
        run: |
          BEFORE_COMMIT="${{ github.event.before || 'HEAD~1' }}"
          CHANGED=$(git diff --name-only "$BEFORE_COMMIT" "${{ github.sha }}" \
            | grep -E '^(modules|templates)/.*\.tf$' \
            | xargs -n1 dirname \
            | sort -u)
          echo "Changed directories:"
          echo "$CHANGED"
          if [ -z "$CHANGED" ]; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "$CHANGED" > changed_dirs.txt
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract ticket ID from last commit
        id: ticket
        shell: bash
        run: |
          TICKET=$(git log -1 --pretty=%B | grep -oE 'NCP-[0-9]+' || echo "NCP-XXXX")
          echo "ticket=$TICKET" >> "$GITHUB_OUTPUT"

      - name: Install terraform-docs
        run: |
          curl -sLo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          sudo mv terraform-docs /usr/local/bin/

      - name: Run terraform-docs on modules and templates directories
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          # Run terraform-docs on the modules directory
          terraform-docs markdown table ./modules --output-file ./modules/README.md --recursive
          
          # Run terraform-docs on the templates directory
          terraform-docs markdown table ./templates --output-file ./templates/README.md --recursive

      - name: Fix Git permissions
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          sudo chown -R "$(whoami)":"$(whoami)" .git/

      - name: Commit and push the updated README.md files
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          git config user.name "tester"
          git config user.email "tester@users.noreply.github.com"

          git add modules/**/README.md templates/**/README.md

          git commit -m "${{ steps.ticket.outputs.ticket }}: Auto-update README.md with terraform-docs" || echo "No changes to commit"

          BRANCH="${GITHUB_REF#refs/heads/}"
          git pull origin "$BRANCH" --rebase
          git push origin "$BRANCH"
