name: Update READMEs with terraform-docs on Merge

on:
  push:
    branches:
      - main
    paths:
      - modules/**/*.tf
      - templates/**/*.tf
      
permissions:
  contents: write

jobs:
  update-readmes:
    name: Update README.md files with terraform-docs (single commit)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract ticket ID from last commit
        id: ticket
        shell: bash
        run: |
          TICKET=$(git log -1 --pretty=%B | grep -oE 'NCP-[0-9]+' || echo "NCP-XXXX")
          echo "ticket=$TICKET" >> "$GITHUB_OUTPUT"
      - name: Get changed Terraform directories
        id: get_dirs
        shell: bash
        run: |
          BEFORE_COMMIT="${{ github.event.before || 'HEAD~1' }}"
          CHANGED=$(git diff --name-only "$BEFORE_COMMIT" "${{ github.sha }}" \
            | grep -E '^(modules|templates)/.*\.tf$' \
            | xargs -n1 dirname \
            | sort -u)
          echo "Changed directories:"
          echo "$CHANGED"
          if [ -z "$CHANGED" ]; then
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "$CHANGED" > changed_dirs.txt
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Install terraform-docs
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
          tar -xzf terraform-docs-v0.19.0-linux-amd64.tar.gz
          sudo mv terraform-docs /usr/local/bin/
          
      - name: Check terraform-docs version
        run: terraform-docs --version

      - name: Run terraform-docs in each directory
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          while read dir; do
            if [ -f "$dir/README.md" ]; then
               echo "Updating $dir/README.md"
               terraform-docs markdown table "$dir" > "$dir/README.md"
            else
               echo "Skipping $dir — no README.md found"
            fi
          done < changed_dirs.txt
          
      - name: Fix Git permissions
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          sudo chown -R "$(whoami)":"$(whoami)" .git/

      - name: Commit and push the updated README.md files
        if: ${{ steps.get_dirs.outputs.no_changes == 'false' }}
        run: |
          git config user.name "tester"
          git config user.email "tester@users.noreply.github.com"

          git add modules/**/README.md templates/**/README.md

          git commit -m "${{ steps.ticket.outputs.ticket }}: Auto-update README.md with terraform-docs" || echo "No changes to commit"

          BRANCH="${GITHUB_REF#refs/heads/}"
          git pull origin "$BRANCH" --rebase
          git push origin "$BRANCH"
